# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win_crabSFM.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CrabsSFM(object):
    def setupUi(self, CrabsSFM):
        CrabsSFM.setObjectName("CrabsSFM")
        CrabsSFM.setWindowModality(QtCore.Qt.WindowModal)
        CrabsSFM.resize(599, 479)
        CrabsSFM.setMinimumSize(QtCore.QSize(599, 479))
        CrabsSFM.setMaximumSize(QtCore.QSize(600, 480))
        CrabsSFM.setSizeGripEnabled(False)
        CrabsSFM.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(CrabsSFM)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_5 = QtWidgets.QFrame(CrabsSFM)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.widget_camera = QtWidgets.QWidget(CrabsSFM)
        self.widget_camera.setObjectName("widget_camera")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_camera)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_Camera = QtWidgets.QCheckBox(self.widget_camera)
        self.checkBox_Camera.setEnabled(False)
        self.checkBox_Camera.setMaximumSize(QtCore.QSize(20, 16777215))
        self.checkBox_Camera.setMouseTracking(False)
        self.checkBox_Camera.setText("")
        self.checkBox_Camera.setCheckable(True)
        self.checkBox_Camera.setTristate(False)
        self.checkBox_Camera.setObjectName("checkBox_Camera")
        self.horizontalLayout.addWidget(self.checkBox_Camera)
        self.label_Camera = QtWidgets.QLabel(self.widget_camera)
        self.label_Camera.setObjectName("label_Camera")
        self.horizontalLayout.addWidget(self.label_Camera)
        self.widget_Approximate_Interior_Orientation = QtWidgets.QWidget(self.widget_camera)
        self.widget_Approximate_Interior_Orientation.setObjectName("widget_Approximate_Interior_Orientation")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_Approximate_Interior_Orientation)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radio_approximate_interion_orientation = QtWidgets.QRadioButton(self.widget_Approximate_Interior_Orientation)
        self.radio_approximate_interion_orientation.setChecked(True)
        self.radio_approximate_interion_orientation.setObjectName("radio_approximate_interion_orientation")
        self.verticalLayout_2.addWidget(self.radio_approximate_interion_orientation)
        self.horizontalLayout.addWidget(self.widget_Approximate_Interior_Orientation)
        self.verticalLayout.addWidget(self.widget_camera)
        self.line = QtWidgets.QFrame(CrabsSFM)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.widget_find_feature_points = QtWidgets.QWidget(CrabsSFM)
        self.widget_find_feature_points.setObjectName("widget_find_feature_points")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_find_feature_points)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_Find_Feature_Points = QtWidgets.QCheckBox(self.widget_find_feature_points)
        self.checkBox_Find_Feature_Points.setEnabled(False)
        self.checkBox_Find_Feature_Points.setMaximumSize(QtCore.QSize(20, 16777215))
        self.checkBox_Find_Feature_Points.setMouseTracking(False)
        self.checkBox_Find_Feature_Points.setCheckable(True)
        self.checkBox_Find_Feature_Points.setObjectName("checkBox_Find_Feature_Points")
        self.horizontalLayout_2.addWidget(self.checkBox_Find_Feature_Points)
        self.label_Find_Feature_Points = QtWidgets.QLabel(self.widget_find_feature_points)
        self.label_Find_Feature_Points.setObjectName("label_Find_Feature_Points")
        self.horizontalLayout_2.addWidget(self.label_Find_Feature_Points)
        self.widget_Feature_Points_Options = QtWidgets.QWidget(self.widget_find_feature_points)
        self.widget_Feature_Points_Options.setObjectName("widget_Feature_Points_Options")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_Feature_Points_Options)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radio_SIFT = QtWidgets.QRadioButton(self.widget_Feature_Points_Options)
        self.radio_SIFT.setEnabled(False)
        self.radio_SIFT.setObjectName("radio_SIFT")
        self.verticalLayout_3.addWidget(self.radio_SIFT)
        self.radio_SURF = QtWidgets.QRadioButton(self.widget_Feature_Points_Options)
        self.radio_SURF.setEnabled(False)
        self.radio_SURF.setObjectName("radio_SURF")
        self.verticalLayout_3.addWidget(self.radio_SURF)
        self.radio_ORB = QtWidgets.QRadioButton(self.widget_Feature_Points_Options)
        self.radio_ORB.setObjectName("radio_ORB")
        self.verticalLayout_3.addWidget(self.radio_ORB)
        self.radio_AKAZE = QtWidgets.QRadioButton(self.widget_Feature_Points_Options)
        self.radio_AKAZE.setChecked(True)
        self.radio_AKAZE.setObjectName("radio_AKAZE")
        self.verticalLayout_3.addWidget(self.radio_AKAZE)
        self.horizontalLayout_2.addWidget(self.widget_Feature_Points_Options)
        self.verticalLayout.addWidget(self.widget_find_feature_points)
        self.line_2 = QtWidgets.QFrame(CrabsSFM)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.widget_Block_Creation = QtWidgets.QWidget(CrabsSFM)
        self.widget_Block_Creation.setObjectName("widget_Block_Creation")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_Block_Creation)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_Block_Creation = QtWidgets.QCheckBox(self.widget_Block_Creation)
        self.checkBox_Block_Creation.setEnabled(False)
        self.checkBox_Block_Creation.setMaximumSize(QtCore.QSize(20, 16777215))
        self.checkBox_Block_Creation.setMouseTracking(False)
        self.checkBox_Block_Creation.setText("")
        self.checkBox_Block_Creation.setCheckable(True)
        self.checkBox_Block_Creation.setObjectName("checkBox_Block_Creation")
        self.horizontalLayout_5.addWidget(self.checkBox_Block_Creation)
        self.label_Block_Creation = QtWidgets.QLabel(self.widget_Block_Creation)
        self.label_Block_Creation.setObjectName("label_Block_Creation")
        self.horizontalLayout_5.addWidget(self.label_Block_Creation)
        self.verticalLayout.addWidget(self.widget_Block_Creation)
        self.line_3 = QtWidgets.QFrame(CrabsSFM)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.widget_image_matching = QtWidgets.QWidget(CrabsSFM)
        self.widget_image_matching.setObjectName("widget_image_matching")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_image_matching)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_Image_Matching = QtWidgets.QCheckBox(self.widget_image_matching)
        self.checkBox_Image_Matching.setEnabled(False)
        self.checkBox_Image_Matching.setMaximumSize(QtCore.QSize(20, 16777215))
        self.checkBox_Image_Matching.setMouseTracking(False)
        self.checkBox_Image_Matching.setText("")
        self.checkBox_Image_Matching.setCheckable(True)
        self.checkBox_Image_Matching.setChecked(False)
        self.checkBox_Image_Matching.setObjectName("checkBox_Image_Matching")
        self.horizontalLayout_3.addWidget(self.checkBox_Image_Matching)
        self.label_Image_Matching = QtWidgets.QLabel(self.widget_image_matching)
        self.label_Image_Matching.setObjectName("label_Image_Matching")
        self.horizontalLayout_3.addWidget(self.label_Image_Matching)
        self.widget_Image_Matching_Options = QtWidgets.QWidget(self.widget_image_matching)
        self.widget_Image_Matching_Options.setObjectName("widget_Image_Matching_Options")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_Image_Matching_Options)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radio_Match_All_Images = QtWidgets.QRadioButton(self.widget_Image_Matching_Options)
        self.radio_Match_All_Images.setChecked(True)
        self.radio_Match_All_Images.setObjectName("radio_Match_All_Images")
        self.verticalLayout_4.addWidget(self.radio_Match_All_Images)
        self.radio_Fast_Matching = QtWidgets.QRadioButton(self.widget_Image_Matching_Options)
        self.radio_Fast_Matching.setObjectName("radio_Fast_Matching")
        self.verticalLayout_4.addWidget(self.radio_Fast_Matching)
        self.horizontalLayout_3.addWidget(self.widget_Image_Matching_Options)
        self.verticalLayout.addWidget(self.widget_image_matching)
        self.line_4 = QtWidgets.QFrame(CrabsSFM)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.widget_Create_Model = QtWidgets.QWidget(CrabsSFM)
        self.widget_Create_Model.setObjectName("widget_Create_Model")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_Create_Model)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_Create_Model = QtWidgets.QCheckBox(self.widget_Create_Model)
        self.checkBox_Create_Model.setEnabled(False)
        self.checkBox_Create_Model.setMaximumSize(QtCore.QSize(20, 16777215))
        self.checkBox_Create_Model.setMouseTracking(False)
        self.checkBox_Create_Model.setText("")
        self.checkBox_Create_Model.setCheckable(True)
        self.checkBox_Create_Model.setObjectName("checkBox_Create_Model")
        self.horizontalLayout_6.addWidget(self.checkBox_Create_Model)
        self.label_Create_Model = QtWidgets.QLabel(self.widget_Create_Model)
        self.label_Create_Model.setObjectName("label_Create_Model")
        self.horizontalLayout_6.addWidget(self.label_Create_Model)
        self.verticalLayout.addWidget(self.widget_Create_Model)
        self.line_6 = QtWidgets.QFrame(CrabsSFM)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget_buttons = QtWidgets.QWidget(CrabsSFM)
        self.widget_buttons.setObjectName("widget_buttons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_buttons)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(388, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.button_cancel = QtWidgets.QPushButton(self.widget_buttons)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout_4.addWidget(self.button_cancel)
        self.button_compute = QtWidgets.QPushButton(self.widget_buttons)
        self.button_compute.setObjectName("button_compute")
        self.horizontalLayout_4.addWidget(self.button_compute)
        self.verticalLayout.addWidget(self.widget_buttons)

        self.retranslateUi(CrabsSFM)
        QtCore.QMetaObject.connectSlotsByName(CrabsSFM)

    def retranslateUi(self, CrabsSFM):
        _translate = QtCore.QCoreApplication.translate
        CrabsSFM.setWindowTitle(_translate("CrabsSFM", "CrabSFM"))
        self.label_Camera.setText(_translate("CrabsSFM", "Camera"))
        self.radio_approximate_interion_orientation.setText(_translate("CrabsSFM", "Approximate Interior Orientation"))
        self.checkBox_Find_Feature_Points.setText(_translate("CrabsSFM", "Find Feature Points"))
        self.label_Find_Feature_Points.setText(_translate("CrabsSFM", "Find Feature Points"))
        self.radio_SIFT.setText(_translate("CrabsSFM", "SIFT"))
        self.radio_SURF.setText(_translate("CrabsSFM", "SURF"))
        self.radio_ORB.setText(_translate("CrabsSFM", "ORB"))
        self.radio_AKAZE.setText(_translate("CrabsSFM", "AKAZE"))
        self.label_Block_Creation.setText(_translate("CrabsSFM", "Block Creation"))
        self.label_Image_Matching.setText(_translate("CrabsSFM", "Image Matching"))
        self.radio_Match_All_Images.setText(_translate("CrabsSFM", "Match All Images"))
        self.radio_Fast_Matching.setText(_translate("CrabsSFM", "Fast Matching"))
        self.label_Create_Model.setText(_translate("CrabsSFM", "Create Model"))
        self.button_cancel.setText(_translate("CrabsSFM", "Cancel"))
        self.button_compute.setText(_translate("CrabsSFM", "Compute"))

